#pragma once

#define PLAYER_CATAGORY (0x1) //0000 0001 
#define ENEMY_CATAGORY (0x2) //0000 0010 
#define PLAYER_BULLET_CATAGORY (0x4) //0000 0100 
#define ENEMY_BULLET_CATAGORY (0x8) //0000 1000 


#define PLAYER_CATAGORY_MASK (ENEMY_CATAGORY)
#define ENEMY_CATAGORY_MASK (PLAYER_CATAGORY | PLAYER_BULLET_CATAGORY)
#define PLAYER_BULLET_CATAGORY_MASK (ENEMY_CATAGORY)
#define ENEMY_BULLET_CATAGORY_MASK (PLAYER_CATAGORY)